/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as stackIndexRouteImport } from './routes/stack/index'
import { Route as projectsIndexRouteImport } from './routes/projects/index'
import { Route as experienceIndexRouteImport } from './routes/experience/index'
import { Route as contactIndexRouteImport } from './routes/contact/index'
import { Route as indexIndexRouteImport } from './routes/index/index'

const stackIndexRoute = stackIndexRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const projectsIndexRoute = projectsIndexRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const experienceIndexRoute = experienceIndexRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const contactIndexRoute = contactIndexRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const indexIndexRoute = indexIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof indexIndexRoute
  '/contact': typeof contactIndexRoute
  '/experience': typeof experienceIndexRoute
  '/projects': typeof projectsIndexRoute
  '/stack': typeof stackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof indexIndexRoute
  '/contact': typeof contactIndexRoute
  '/experience': typeof experienceIndexRoute
  '/projects': typeof projectsIndexRoute
  '/stack': typeof stackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof indexIndexRoute
  '/contact': typeof contactIndexRoute
  '/experience': typeof experienceIndexRoute
  '/projects': typeof projectsIndexRoute
  '/stack': typeof stackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/experience' | '/projects' | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/experience' | '/projects' | '/stack'
  id: '__root__' | '/' | '/contact' | '/experience' | '/projects' | '/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  indexIndexRoute: typeof indexIndexRoute
  contactIndexRoute: typeof contactIndexRoute
  experienceIndexRoute: typeof experienceIndexRoute
  projectsIndexRoute: typeof projectsIndexRoute
  stackIndexRoute: typeof stackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof stackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof projectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof experienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof contactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof indexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexIndexRoute: indexIndexRoute,
  contactIndexRoute: contactIndexRoute,
  experienceIndexRoute: experienceIndexRoute,
  projectsIndexRoute: projectsIndexRoute,
  stackIndexRoute: stackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
